"use strict";
exports.__esModule = true;
var Company_1 = require("./Company");
var Employee_1 = require("./Employee");
var CompanyArrayLocation_1 = require("./CompanyArrayLocation");
var CompanyLocalStorageLocation_1 = require("./CompanyLocalStorageLocation");
var location1 = new CompanyArrayLocation_1["default"](['a', 'b', 'c']);
var location2 = new CompanyArrayLocation_1["default"](['c', 'd', 'e']);
var location3 = new CompanyLocalStorageLocation_1["default"]('a');
location3.addPerson('Piter');
location3.addPerson('Parker');
var location4 = new CompanyLocalStorageLocation_1["default"]('b');
location4.addPerson('Vasia');
location4.addPerson('Petia');
var company1 = new Company_1["default"](location1);
var company2 = new Company_1["default"](location2);
var company3 = new Company_1["default"](location3);
var company4 = new Company_1["default"](location4);
company1.add(new Employee_1["default"]('pikasso1', 'ahaha1'));
company1.add(new Employee_1["default"]('pikasso2', 'ahaha2'));
company1.add(new Employee_1["default"]('pikasso3', 'ahaha3'));
company2.add(new Employee_1["default"]('cur project1', 'ahaha4'));
company2.add(new Employee_1["default"]('cur project2', 'ahaha5'));
company2.add(new Employee_1["default"]('cur project3', 'ahaha6'));
company3.add(new Employee_1["default"]('b1', 'ahaha7'));
company3.add(new Employee_1["default"]('b2', 'ahaha8'));
company3.add(new Employee_1["default"]('b4', 'ahaha9'));
company4.add(new Employee_1["default"]('c1', 'ahaha11'));
company4.add(new Employee_1["default"]('c2', 'ahaha12'));
company4.add(new Employee_1["default"]('c3', 'ahaha13'));
console.log("company1.getNameList() = " + company1.getNameList());
console.log('company1.getProjectList() = ' + company1.getProjectList());
console.log('company1.getLocationPeople() = ' + company1.getLocationPeople());
console.log("company2.getNameList() = " + company2.getNameList());
console.log('company2.getProjectList() = ' + company2.getProjectList());
console.log('company2.getLocationPeople() = ' + company2.getLocationPeople());
console.log("company3.getNameList() = " + company3.getNameList());
console.log('company3.getProjectList() = ' + company3.getProjectList());
console.log('company3.getLocationPeople() = ' + company3.getLocationPeople());
console.log("company4.getNameList() = " + company4.getNameList());
console.log('company4.getProjectList() = ' + company4.getProjectList());
console.log('company4.getLocationPeople() = ' + company4.getLocationPeople());
//# sourceMappingURL=SomeRunner.js.map